### PR TITLE
Fix the sample applications to be able to build with Java 21

### PR DESCRIPTION
**Pull request by KodaiD**
## Description

Our sample applications should be able to built with the Java versions we support (Java 8, 11, 17, 21). 

As a result of PR #70, our examples now work with Java 8, 11 and 17. However, most ScalarDB sample applications use Gradle 7.6 that does not support Java 21. 

To address this issue, I try to upgrade the version of Gradle to 8.5 in this PR. I also try to eliminate the docker plugin that is not compatible with all Java versions we support.

## Related issues and/or PRs

- https://github.com/scalar-labs/scalardb-samples/pull/70

## Changes made

- Upgrade the version of Gradle to 8.5
- Remove docker plugin

## Checklist

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation to reflect the changes.
- [x] Any remaining open issues linked to this PR are documented and up-to-date (Jira, GitHub, etc.).
- [x] Tests (unit, integration, etc.) have been added for the changes.
- [x] My changes generate no new warnings.
- [x] Any dependent changes in other PRs have been merged and published.

## Additional notes (optional)

N/A

### CODE REVIEW

**Comment by KodaiD** [comment]
I've confirmed that the all samples are able to build with Java 21. I've also confirmed that I can run/try microservice-transaction-sample and spring-data-microservice-transaction-sample following their documents.

**Comment by KodaiD** [comment]
> @KodaiD So, unlike the ScalarDL samples, we don't need to use Toolchain in the ScalarDB samples. Is my understanding correct? If yes, what’s the difference?

Strictly speaking, we don't need to use the toolchain in both the ScalarDB sample and ScalarDL sample. But, in the update of ScalarDL sample, I tried to remove all warnings appearing when we built it.

sourceCompatibility and targetCompatibility seem to be deprecated, and the following error appears when building.

```
> Task :compileJava
警告: [options] ソース値8は廃止されていて、今後のリリースで削除される予定です
警告: [options] ターゲット値8は廃止されていて、今後のリリースで削除される予定です
```

Of course I can fix the sample to use the toolchain instead, but I think this it's outside the scope of this PR (I think the main target of this PR is making the sample to be able to build on Java 21).

**Review by komamitsu — APPROVED** [review]
LGTM! 👍

**Comment by brfrn169** [comment]
@KodaiD Thank you for answering my question.

> Of course I can fix the sample to use the toolchain instead, but I think this it's outside the scope of this PR (I think the main target of this PR is making the sample to be able to build on Java 21).

I think we should fix the samples to use the toolchain for consistency. Let's do that in a separate PR. Thanks.

**Review by brfrn169 — APPROVED** [review]
LGTM! Thank you!

**Review by kota2and3kan — APPROVED** [review]
LGTM! Thank you!

FYI: I didn't test all samples, but I was able to run the `./gradlew docker` command under the `spring-data-microservice-transaction-sample/` directory by using Java 8, 11, 17, and 21 in my local environment.

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
