### PR TITLE
Fix broken links, headings, and formatting for consistency

### PR DESCRIPTION
**Pull request by josh-wong**
## Description

This PR contains some minor fixes to sample tutorials.

## Related issues and/or PRs

N/A

## Changes made

- Fix broken link that points to the ScalarDB sample tutorial.
- Fix heading indentation.
- Change heading title for consistency with other sample tutorials.

## Checklist

> The following is a best-effort checklist. If any items in this checklist are not applicable to this PR or are dependent on other, unmerged PRs, please still mark the checkboxes after you have read and understood each item.

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation to reflect the changes.
- [x] Any remaining open issues linked to this PR are documented and up-to-date (Jira, GitHub, etc.).
- [x] Tests (unit, integration, etc.) have been added for the changes.
- [x] My changes generate no new warnings.
- [x] Any dependent changes in other PRs have been merged and published.

## Additional notes (optional)

N/A

## Release notes

N/A

### CODE REVIEW

**Review by komamitsu — APPROVED** [review]
LGTM! 👍

**Review by brfrn169 — APPROVED** [review]
LGTM! Thank you!

**Comment by brfrn169** [comment]
@josh-wong BTW, as I commented [here](https://github.com/scalar-labs/scalardb-samples/pull/51#issuecomment-1742984854), I don't think we don't need the `Release notes` section in the PR description. Can you please remove it from the PR template?

**Comment by josh-wong** [comment]
> @josh-wong BTW, as I commented [here](https://github.com/scalar-labs/scalardb-samples/pull/51#issuecomment-1742984854), I don't think we need the `Release notes` section in the PR description. Can you please remove it from the PR template?

@brfrn169 Ah sorry, I missed your original comment about the `Release note` section. I'll remove it in another PR.

**Pull request merged**
