### PR TITLE
Revise README in Microservice Transaction Sample

### PR DESCRIPTION
**Pull request by brfrn169**
This PR modifies the README of the Microservices Transaction Sample to reflect the changes made in https://github.com/scalar-labs/scalardb-samples/pull/29. Please take a look!

### CODE REVIEW

**Comment by komamitsu** [comment]
> to reflect the changes made in https://github.com/scalar-labs/scalardb-samples/pull/29

And the actual change was https://github.com/scalar-labs/scalardb/pull/715 ?

**Review by komamitsu — APPROVED** [review]
LGTM! 👍

**Comment by brfrn169** [comment]
> And the actual change was [scalar-labs/scalardb#715](https://github.com/scalar-labs/scalardb/pull/715) ?

@komamitsu Yes, correct.

**Review by Torch3333 — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
