### PR TITLE
Add ScalarDB with Kotlin sample

### PR DESCRIPTION
**Pull request by brfrn169**
## Description

This PR adds ScalarDB with Kotlin sample. This is basically copied from https://github.com/scalar-labs/scalardb/tree/master/docs/getting-started-kotlin.

## Related issues and/or PRs

N/A

## Changes made

- Added ScalarDB with Kotlin sample.

## Checklist

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation to reflect the changes.
- [x] Any remaining open issues linked to this PR are documented and up-to-date (Jira, GitHub, etc.).
- [x] Tests (unit, integration, etc.) have been added for the changes.
- [x] My changes generate no new warnings.
- [x] Any dependent changes in other PRs have been merged and published.

## Additional notes (optional)

N/A

### CODE REVIEW

**Review by josh-wong — APPROVED** [review]
LGTM! As mentioned in https://github.com/scalar-labs/docs-internal-scalardb/pull/246#pullrequestreview-2206877310, I was able to run this sample application locally by following the instructions in the updated doc👍

Thank you!🙇🏻‍♂️

**Review by Torch3333 — APPROVED** [review]
LGTM, thank you!

**Review by komamitsu — APPROVED** [review]
LGTM! 👍

**Comment by komamitsu** [comment]
@brfrn169 Just noticed [this build test in CI](https://github.com/scalar-labs/scalardb/pull/2127/files#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133ddL138-L159) wasn't copied. Is it okay?

**Comment by brfrn169** [comment]
@komamitsu 

> @brfrn169 Just noticed [this build test in CI](https://github.com/scalar-labs/scalardb/pull/2127/files#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133ddL138-L159) wasn't copied. Is it okay?

Thanks. @KodaiD will do that.

**Review by kota2and3kan — APPROVED** [review]
LGTM! Thank you!

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
